# Generated by Django 4.0.5 on 2022-07-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_forgetpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetpassword',
            old_name='Accounts',
            new_name='accounts',
        ),
    ]
